### ISSUE TITLE
PHP API

### ISSUE THREAD

**Issue by TheRatG** [phpv8/php-v8#109]
Hello, thanks for lib and easy installation. Where I can find PHP API, description of classes and functions?

**Comment by pinepain** [comment]
Hi, the best documentation on the API you can find in [stubs](https://github.com/phpv8/php-v8/tree/master/stubs) folder. Stubs are also available via composer with `composer require --dev pinepain/php-v8-stubs`. Unfortunately, the official docs (https://php-v8.readthedocs.io/en/latest/) is still in development, so stubs, tests and [js-sandbox](https://github.com/phpv8/js-sandbox) are you friends for now.

Do not hesitate to write back if you have any questions. PRs are welcomed too 😄

**Comment by TheRatG** [comment]
Thanks @pinepain
